name: Set PR Title
run-name: ${{ github.actor }} is setting the title of the Pull Request 🚀

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  set_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set PR Title
        uses: actions/github-script@v7
        with:
          script: |
            const { VERSION } = process.env
            github.rest.pulls.update({
              title: 'This title was set by a GitHub Action!'
            }).then(function(result) {
              core.info(`Release ${result.data.name} found`)
              return result.data.name
            }).catch(function(error) {
              if (error.status === 404) {
                core.info(`Release v${VERSION} not found`)
                return
              } else {
                throw error
              }
            })

      # - uses: gr2m/create-or-update-pull-request-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: "This title was set by a GitHub Action!"
      #     update-pull-request-title-and-body: true
