name: Set PR title

on:
  pull_request:
    types:
      - opened

jobs:
  set-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set PR title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.update({
              title: "This title was set by a GitHub Action!",
            });
            